package com.interbio.precheckimagequality

data class PrecheckImageQualityConfiguration(
    var license: String = "",
    var colorOverlay: String = "",
    var colorOverlayOpacity: Double = 0.5,
    var colorBorderGood: String = "",
    var colorBorderBad: String = "",
    var colorCheckmark: String = "",
    var colorCheckmarkOpacity: Double = 0.5,
    var colorCaptureButton: String = "",
    var colorCaptureText: String = "",
    var autoCapture: Boolean = true,
    var delayCheckmark: Double = 0.3,
    var delayAutoCapture: Double = 1.0,
    var messageLoading: String = "Sedang Memproses Kamera",
    var messageNoFaceDetected: String = "Wajah Tidak Terdeteksi",
    var messageMultipleFaceDetected: String = "Terdeteksi Lebih dari 1 Wajah",
    var messageCenterYourFace: String = "Pusatkan Wajah Anda Ke Tengah",
    var messageMoveFaceAway: String = "Pindahkan Wajah Lebih Jauh",
    var messageMoveFaceCloser: String = "Pindahkan Wajah Lebih Dekat",
    var messageLookStraight: String = "Lihat ke Depan",
    var messageEyesClosed: String = "Mata Tertutup",
    var messageKeepStill: String = "Tahan, Jangan Bergerak",
    var messageMaskDetected: String = "Masker Terdeteksi",
    var messageHatDetected: String = "Topi Terdeteksi",
    var messageGlassesDetected: String = "Kacamata Terdeteksi",
    var sensitivityYawStart: Double = -25.0,
    var sensitivityYawEnd: Double = 25.0,
    var sensitivityRollStart: Double = -15.0,
    var sensitivityRollEnd: Double = 15.0,
    var sensitivityPitchStart: Double = -20.0,
    var sensitivityPitchEnd: Double = 20.0,
    var sensitivityGlasses: Double = 0.7,
    var sensitivityMask: Double = 0.9,
    var sensitivityHat: Double = 0.75,
    var sensitivityBlur: Double = 0.9,
    var sensitivityPositionXStart: Double = 0.05,
    var sensitivityPositionXEnd: Double = 0.20,
    var sensitivityPositionYStart: Double = 0.25,
    var sensitivityPositionYEnd: Double = 0.50,
    var sensitivityPositionHStart: Double = 0.45,
    var sensitivityPositionHEnd: Double = 0.70,
    var timeoutEnabled: Boolean = false,
    var timeoutTime: Double = 10.0,
    var etcFailOnMultipleFace: Boolean = false
)
